#' #postgresql
#'
#' #' Hook into postgres database
#' #' @description Either pull information out, or append new information
#' #' @param new_df = dataframe to append to current database
#' #' @param append = whether to append the database or not
#' #' @return  nothing
#' #' @export
#' postgres_append <- function(new_df = NULL, append = FALSE){
#'
#'   # appends df to the PostgreSQL database "postgres", table "indeed_info"
#'     if(append == TRUE){
#'     key <- dbGetQuery(con, 'SELECT job_key from indeed_info')
#'     new_df <- new_df %>% filter(!(job_key %in% key$job_key))
#'     new_df <- new_df %>% filter(!duplicated(job_key))
#'     dbWriteTable(con, "indeed_info",
#'                value = new_df, append = TRUE, row.names = FALSE, overwrite = FALSE)
#'     cat("Data has been appended to database")
#'     }
#' }
#'






#' Allows the user to query the postgres database for search terms or location
#'
#' @param db_search_term = job term to search the database for
#' @param db_location = location to query database
#' @param lim = limit the number of jobs to extract
#' @return overwrites the old rdata file with an updated version
#' (you can never remove existing terms, only add new ones)
#' @export
#'
query_database <- function(db_search_term = "", db_location = "", lim = 10000){

  db <- NULL

  #clean search input to remove special characters
  location <- clean_text(text = db_location, for_query = TRUE)
  location <- unlist(strsplit(location, split = " "))
  location <- paste0("'",paste(location,collapse = " |"), " '")
  search_term <- clean_text(text = db_search_term, for_query = TRUE)
  search_term <- unlist(strsplit(search_term, split = " "))
  search_term <- paste0("'",paste(search_term,collapse = " "), "'")

  # both, search, loc ,and none objects are used to determine how to query the database
  #if both then we will query based on location and search
  #if search then query only on search term
  #if loc then query analyst based on location
  #if  none then query the entire database
  #all the objects are boolean
  both <- db_search_term != "" && db_location != ""

  if(!both){
    search <- db_search_term != ""
    loc <- db_location != ""
    none <- sum(c(both, search, loc)) == 0
  }

  #use regular expressions to find matches on location and search term
  if(both){
    query <- paste0("select * from indeed_info where lower(job_title) ~  ",search_term,
                     " AND lower(concat(state,city)) ~ ",location,
                    " limit ", lim)
    db <- dbGetQuery(con, query)
    cat("queried database for",db_search_term, "in", db_location )
    cat("\n")
  }else if(none){  #query the entire database
    query <- paste0("select * from indeed_info limit ", lim)
    db <- dbGetQuery(con, query)
    cat("queried all database jobs")
    cat("\n")
  }else if(search){ #query job title and previous search terms using regular expressions (regex)
    query <- paste0("select * from indeed_info where lower(job_title) ~  ",search_term,
                    " limit ", lim)
    db <- dbGetQuery(con, query)
    cat("queried database for",db_search_term)
    cat("\n")
  } else if(loc){ #query the location using regex
    query <- paste0("select * from indeed_info where lower(concat(state,city)) ~ ",location, " limit ", lim)
    db <- dbGetQuery(con, query)
    cat("queried database for jobs in ",location)
    cat("\n")
  }

  if(nrow(db) > 0){
  db %>%  #trim whitespace generated by postgres
    mutate_each(funs(replace(., . != "", trimws(.))),
                -c(date, years_exp, degree_preferred, last_checked_date)) -> db
    return(db)
  }


}






#' updates the postgres db by removing old jobs
#'
#' @description this function identifies all jobs over a week old. It then queries the indeed api
#' to determine whether the job has expired or not. If it is then the row is deleted and moved into
#' the old_indeed_info table
#' @param num_days = a filter for which jobs to check.. how many days old are the jobs you want to check
#' @param lim = the max number of jobs to query
#' @export
#'
update_db <- function(num_days = 7, lim = 1000){
  delete_rows <- NULL
  #grab keys of jobs which jobs are over 7 days old
  key_query <- paste0("select job_key from indeed_info where (Current_date - last_checked_date) > ", num_days)
  job_keys <- dbGetQuery(con, key_query)

  lim <- ifelse(nrow(job_keys) > lim, lim, nrow(job_keys))
  job_keys <- job_keys[1:lim,]

  #loops through each key and determines if the job is expired.
  for (key in job_keys) {
    print(key)
    delete_row <- NULL

    #grap api info for specific key
    api <- paste0('http://api.indeed.com/ads/apigetjobs?publisher=5795537109414523&jobkeys=',key,'&v=2')
    xml_file <- GET(api)
    xml_file <- httr::content(xml_file)

    #extract expired info
    xml_file %>%
      html_nodes('expired') %>%
      html_text() -> expired


    #if the key is expired store it to be deleted later
    if(length(expired) > 0 && expired == 'true'){
      delete_rows <- c(delete_row,paste0("'",key,"'"))
    }

  }

  update_job_keys <- paste(job_keys, collapse = "','")
  update_query <- paste0("UPDATE indeed_info SET last_checked_date = Current_date where ",
                         "job_key in ('", update_job_keys, "')")
  dbSendQuery(con, update_query) #update the last_checked_date
  cat('updated last_checked_date_col')
  cat('\n')

  #once expired jobs have been found, add those rows to the old_indeed_info table
  #and then delete those rows out of indeed_info
    if(!is.null(delete_rows)){

      #create sql query to delete the jobs
      delete_rows <- paste(delete_rows, collapse = ",")
      delete_query <- paste0("DELETE from indeed_info where job_key in (", delete_rows, ")")

      #create sql query to extract the jobs
      add_query <- paste0("Select * from indeed_info where job_key in (", delete_rows, ")")
      add_rows <-dbGetQuery(con, add_query)

      #use add_rows query to add old jobs to old_indeed_info table
      add.new.rows <- dbWriteTable(con, "old_indeed_info",
                     value = add_rows, append = TRUE, row.names = FALSE, overwrite = FALSE)

      #if the rows were added successfullly then delete them from the old table
      if(add.new.rows == TRUE){
        dbGetQuery(con, delete_query)
        cat('Deleted old jobs, stored them in old_indeed_info')
      }
    } else{cat('\n')
           cat('no jobs to update')}

}











